# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: frequenz/api/common/v1/pagination/pagination_info.proto, frequenz/api/common/v1/pagination/pagination_params.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import Optional

import betterproto


@dataclass(eq=False, repr=False)
class PaginationInfo(betterproto.Message):
    """
    A message providing metadata about paginated list results. The
    PaginationInfo message delivers metadata concerning the paginated list
    results and should be appended to the response message of a list request.
    The total_items field must be set to the total count of items that adhere
    to the filter criteria defined in the request. The next_page_token field
    should be populated with the token to be used in the subsequent request to
    fetch the next page of results. If there are no additional results, the
    next_page_token field should be omitted.
    """

    total_items: int = betterproto.uint32_field(1)
    """
    The total number of items that match the filter criteria defined in the
    request.
    """

    next_page_token: Optional[str] = betterproto.string_field(
        2, optional=True, group="_next_page_token"
    )
    """Token for retrieving the next set of results."""


@dataclass(eq=False, repr=False)
class PaginationParams(betterproto.Message):
    """
    A message defining parameters for paginating list requests. It can be
    appended to a request message to specify the desired page of results and
    the maximum number of results per page. For initial requests (requesting
    the first page), the page_token should not be provided. For subsequent
    requests (requesting any page after the first), the next_page_token from
    the previous responses PaginationInfo must be supplied. The page_size
    should only be specified in the initial request and will be disregarded in
    subsequent requests.
    """

    page_size: Optional[int] = betterproto.uint32_field(
        1, optional=True, group="_page_size"
    )
    """The maximum number of results to be returned per request."""

    page_token: Optional[str] = betterproto.string_field(
        2, optional=True, group="_page_token"
    )
    """The token identifying a specific page of the list results."""
